name: PHP

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:
    name: Build, lint and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2']
    steps:

      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check coding standard
        run: ./vendor/bin/phpcs --standard=phpcs.xml

      - name: Run test suites
        run: |
          mkdir ../code-coverage-php-html-${{ matrix.php-versions }}
          ./vendor/bin/phpunit -c phpunit.xml --coverage-clover ../code-coverage-php-clover-${{ matrix.php-versions }}.xml --coverage-html ../code-coverage-php-html-${{ matrix.php-versions }}

      - name: Upload code coverage report to GH
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-php-html-${{ matrix.php-versions }}
          path: ./code-coverage-php-html-${{ matrix.php-versions }}
          retention-days: 7

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./code-coverage-php-clover-${{ matrix.php-versions }}.xml
